Bound Julia version due to RuntimeGeneratedFunction problem on 1.6
```julia
using RuntimeGeneratedFunctions
RuntimeGeneratedFunctions.init(@__MODULE__)
ex = :(function foo(a, b)
    goo = function (c, d)
    end
end)
fun = @RuntimeGeneratedFunction(ex)
fun(1, 2)
```
gives
```julia
julia> fun(1, 2)
ERROR: The function body AST defined by this @generated function is not pure. This likely means it contains a closure or comprehension.
Stacktrace:
 [1] (::RuntimeGeneratedFunction{(:a, :b), var"#_RGF_ModTag", var"#_RGF_ModTag", (0x1c41534f, 0x444455e2, 0x6114b514, 0xa7b18630, 0x10e959a2)})(::Int64, ::Int64)
   @ RuntimeGeneratedFunctions ~/.julia/packages/RuntimeGeneratedFunctions/6v5Gn/src/RuntimeGeneratedFunctions.jl:124
 [2] top-level scope
   @ REPL[47]:1
```